import type {
  AggregatedMetric,
  AuditResult,
  FrameNode,
  Report,
} from "@ohmyperf/core";
import { escapeHtml, escapeJsonForHtml } from "./escape.js";
import { VIEWER_CSS } from "./styles.js";

export interface RenderViewerOptions {
  readonly title?: string;
  readonly embedReportPayload?: boolean;
}

const HEADLINE_METRICS: ReadonlyArray<{
  name: string;
  unit: "ms" | "score";
  digits: number;
}> = [
  { name: "lcp", unit: "ms", digits: 1 },
  { name: "fcp", unit: "ms", digits: 1 },
  { name: "ttfb", unit: "ms", digits: 1 },
  { name: "inp", unit: "ms", digits: 1 },
  { name: "cls", unit: "score", digits: 3 },
  { name: "tbt", unit: "ms", digits: 1 },
];

const UNSTABLE_COV_THRESHOLD = 0.2;

export function renderReportHtml(report: Report, opts: RenderViewerOptions = {}): string {
  const title = opts.title ?? `OhMyPerf — ${shortenUrl(report.meta.url)}`;
  const embedPayload = opts.embedReportPayload !== false;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<meta name="generator" content="@ohmyperf/viewer 0.0.0-pre" />
<meta name="referrer" content="no-referrer" />
<title>${escapeHtml(title)}</title>
<style>${VIEWER_CSS}</style>
</head>
<body>
<div class="container">
  ${renderHeader(report)}
  ${renderUnstableBanner(report)}
  ${renderTiles(report)}
  ${renderAudits(report.audits)}
  ${renderFrameTree(report)}
  ${renderRunsTable(report)}
  ${renderPluginData(report.pluginData)}
  ${renderRawJson(report)}
  <p class="foot">
    Generated by <code>@ohmyperf/viewer</code>. This file is self-contained:
    no external network requests are made when you open it.
  </p>
</div>
${embedPayload ? renderInlineReport(report) : ""}
</body>
</html>
`;
}

function renderHeader(report: Report): string {
  const m = report.meta;
  return `<div class="panel">
  <h1>OhMyPerf v${escapeHtml(report.schemaVersion)} report</h1>
  <dl class="meta">
    <dt>URL</dt><dd class="mono">${escapeHtml(m.url)}</dd>
    <dt>Started</dt><dd>${escapeHtml(m.startedAt)}</dd>
    <dt>Duration</dt><dd>${escapeHtml(`${String(m.durationMs)} ms`)}</dd>
    <dt>Mode</dt><dd>${escapeHtml(m.mode)} · runs=${escapeHtml(String(m.runs))} · ${escapeHtml(m.parity.mode)}</dd>
    <dt>Browser</dt><dd>${escapeHtml(`${m.browser.name} ${m.browser.version} (${m.browser.source})`)}</dd>
    <dt>Host</dt><dd>${escapeHtml(`${m.host.os} (${m.host.arch}) · Node ${m.host.nodeVersion}`)}</dd>
    <dt>Measurement ID</dt><dd class="mono">${escapeHtml(m.measurementId)}</dd>
  </dl>
</div>`;
}

function renderUnstableBanner(report: Report): string {
  const unstable = isUnstable(report);
  if (!unstable) return "";
  return `<div class="unstable-banner">
  <strong>Unstable run.</strong> At least one Core Web Vital has CoV &gt; ${escapeHtml(String(UNSTABLE_COV_THRESHOLD * 100))}% across the ${escapeHtml(String(report.runs.length))} run(s). Increase <code>--runs</code> or use <code>--mode ci-stable</code> for budget gating.
</div>`;
}

function isUnstable(report: Report): boolean {
  if (report.meta.unstable === true) return true;
  for (const name of ["lcp", "cls", "inp", "fcp", "ttfb"]) {
    const agg = report.aggregated[name];
    if (agg && Number.isFinite(agg.cov) && agg.cov > UNSTABLE_COV_THRESHOLD) return true;
  }
  return false;
}

function renderTiles(report: Report): string {
  const tiles = HEADLINE_METRICS.map(({ name, unit, digits }) => {
    const agg = report.aggregated[name];
    return renderTile(name, agg, unit, digits);
  })
    .filter((s) => s.length > 0)
    .join("\n");
  if (tiles.length === 0) return "";
  return `<h2>Aggregated metrics</h2>
<div class="tiles">
${tiles}
</div>`;
}

function renderTile(
  name: string,
  agg: AggregatedMetric | undefined,
  unit: "ms" | "score",
  digits: number,
): string {
  if (!agg) return "";
  const unstable = Number.isFinite(agg.cov) && agg.cov > UNSTABLE_COV_THRESHOLD;
  const median = agg.median.toFixed(digits);
  const display = unit === "ms" ? `${median} ms` : median;
  const cov = Number.isFinite(agg.cov) ? `${(agg.cov * 100).toFixed(1)}%` : "—";
  return `  <div class="tile${unstable ? " unstable" : ""}">
    <div class="name">${escapeHtml(name.toUpperCase())}</div>
    <div class="value">${escapeHtml(display)}</div>
    <div class="sub">cov ${escapeHtml(cov)} · n=${escapeHtml(String(agg.runs))}${unstable ? " · unstable" : ""}</div>
  </div>`;
}

function renderAudits(audits: ReadonlyArray<AuditResult>): string {
  if (audits.length === 0) return "";
  const rows = audits
    .map((a) => {
      const status = a.passed ? "pass" : "fail";
      const label = a.passed ? "PASS" : "FAIL";
      return `    <tr>
      <td><span class="tag ${escapeHtml(status)}">${escapeHtml(label)}</span></td>
      <td class="mono">${escapeHtml(a.id)}</td>
      <td>${escapeHtml(a.title)}</td>
      <td>${a.score === null ? "<span class=\"muted\">—</span>" : escapeHtml(String(a.score))}</td>
    </tr>`;
    })
    .join("\n");
  return `<h2>Audits</h2>
<div class="panel" style="padding:0;overflow:hidden;">
  <table>
    <thead><tr><th>Status</th><th>ID</th><th>Title</th><th>Score</th></tr></thead>
    <tbody>
${rows}
    </tbody>
  </table>
</div>`;
}

function renderFrameTree(report: Report): string {
  const tree = report.frames;
  if (!tree.root || !tree.nodes[tree.root]) return "";
  const html = renderFrameNode(tree.nodes, tree.root);
  return `<h2>Frame tree</h2>
<div class="panel frame-tree">
${html}
</div>`;
}

function renderFrameNode(
  nodes: Readonly<Record<string, FrameNode>>,
  frameId: string,
): string {
  const node = nodes[frameId];
  if (!node) return "";
  const childrenHtml = node.children.length
    ? `<ul>${node.children.map((id) => `<li>${renderFrameNode(nodes, id)}</li>`).join("")}</ul>`
    : "";
  const tagBits: string[] = [];
  if (node.isOOPIF) tagBits.push("OOPIF");
  if (node.isCrossOrigin) tagBits.push("cross-origin");
  if (node.isSrcdoc) tagBits.push("srcdoc");
  if (node.isFenced) tagBits.push("fenced-frame");
  if (node.detachedAt !== undefined) tagBits.push("detached");
  const tags = tagBits.length
    ? ` <span class="tag warn">${escapeHtml(tagBits.join(" · "))}</span>`
    : "";
  const opaqueReason = node.inFrameMetrics?.available === false ? node.inFrameMetrics.reason : "";
  const opaque = opaqueReason
    ? ` <span class="tag warn">opaque: ${escapeHtml(opaqueReason)}</span>`
    : "";
  return `<div>
  <div><strong>${escapeHtml(node.frameId)}</strong>${tags}${opaque}</div>
  <div class="frame-url">${escapeHtml(node.url || "(empty)")}</div>
  ${childrenHtml}
</div>`;
}

function renderRunsTable(report: Report): string {
  if (report.runs.length === 0) return "";
  const metricNames = collectMetricNames(report);
  if (metricNames.length === 0) return "";
  const headerRow = `<tr><th>Run</th><th>Cold</th>${metricNames
    .map((n) => `<th class="mono">${escapeHtml(n)}</th>`)
    .join("")}</tr>`;
  const bodyRows = report.runs
    .map((r) => {
      const cells = metricNames
        .map((n) => {
          const m = r.metrics[n];
          if (!m || !Number.isFinite(m.value)) return `<td class="muted">—</td>`;
          const digits = n === "cls" ? 3 : 1;
          return `<td class="mono">${escapeHtml(m.value.toFixed(digits))}</td>`;
        })
        .join("");
      return `<tr><td>${escapeHtml(String(r.runIndex))}</td><td>${
        r.cold ? `<span class="tag warn">cold</span>` : ""
      }</td>${cells}</tr>`;
    })
    .join("\n");
  return `<h2>Per-run values</h2>
<div class="panel" style="padding:0;overflow:hidden;">
  <table>
    <thead>${headerRow}</thead>
    <tbody>${bodyRows}</tbody>
  </table>
</div>`;
}

function collectMetricNames(report: Report): string[] {
  const seen = new Set<string>();
  for (const r of report.runs) {
    for (const k of Object.keys(r.metrics)) seen.add(k);
  }
  return [...seen].sort();
}

function renderPluginData(pluginData: Readonly<Record<string, unknown>>): string {
  const keys = Object.keys(pluginData);
  if (keys.length === 0) return "";
  const blocks = keys
    .map((k) => {
      const json = JSON.stringify(pluginData[k], null, 2);
      return `<details>
  <summary>${escapeHtml(k)}</summary>
  <pre class="code">${escapeHtml(json)}</pre>
</details>`;
    })
    .join("\n");
  return `<h2>Plugin data</h2>
<div class="panel">
${blocks}
</div>`;
}

function renderRawJson(report: Report): string {
  const json = JSON.stringify(report, null, 2);
  return `<h2>Raw report</h2>
<details>
  <summary>Show raw JSON</summary>
  <pre class="code">${escapeHtml(json)}</pre>
</details>`;
}

function renderInlineReport(report: Report): string {
  return `<script type="application/json" id="ohmyperf-report-payload">${escapeJsonForHtml(report)}</script>
<script>
  (function () {
    try {
      var el = document.getElementById("ohmyperf-report-payload");
      if (el && el.textContent) {
        window.__OHMYPERF_REPORT__ = JSON.parse(el.textContent);
      }
    } catch (e) {
      console.warn("ohmyperf: could not parse embedded report payload", e);
    }
  })();
</script>`;
}

function shortenUrl(url: string): string {
  try {
    const u = new URL(url);
    return `${u.host}${u.pathname === "/" ? "" : u.pathname}`;
  } catch {
    return url;
  }
}
