import type {
  AggregatedMetric,
  AuditResult,
  FrameNode,
  Report,
  RunReport,
} from "@ohmyperf/core";
import { BRAND_MANIFEST, getBrandCss, isBrandId, type BrandId } from "@ohmyperf/design-tokens";
import { escapeHtml, escapeJsonForHtml } from "./escape.js";
import { renderCwvGrid } from "./sections/cwv-cards.js";
import { renderEmptyState } from "./sections/empty-state.js";
import { renderHero } from "./sections/hero.js";
import { renderThirdParties } from "./sections/third-parties.js";
import { STRUCTURAL_CSS } from "./styles.js";
import { BRAND_STRUCTURAL_OVERRIDES } from "./structural-overrides.js";

export interface RenderViewerOptions {
  readonly title?: string;
  readonly embedReportPayload?: boolean;
  readonly theme?: "light" | "dark" | "system";
  readonly style?: BrandId;
}

const HEADLINE_METRICS: ReadonlyArray<{
  name: string;
  unit: "ms" | "score";
  digits: number;
}> = [
  { name: "lcp", unit: "ms", digits: 1 },
  { name: "fcp", unit: "ms", digits: 1 },
  { name: "ttfb", unit: "ms", digits: 1 },
  { name: "inp", unit: "ms", digits: 1 },
  { name: "cls", unit: "score", digits: 3 },
  { name: "tbt", unit: "ms", digits: 1 },
];

const UNSTABLE_COV_THRESHOLD = 0.2;

export function renderReportHtml(report: Report, opts: RenderViewerOptions = {}): string {
  const title = opts.title ?? `OhMyPerf — ${shortenUrl(report.meta.url)}`;
  const embedPayload = opts.embedReportPayload !== false;
  const style: BrandId = isBrandId(opts.style) ? opts.style : "calibre";
  const themeClass = opts.theme === "light" ? "theme-light" : opts.theme === "dark" ? "theme-dark" : "";
  const paletteCss = getBrandCss(style, opts.theme ?? "system");
  const manifest = BRAND_MANIFEST[style];
  const isCalibre = style === "calibre";
  const attributionSuffix = isCalibre ? "" : ` · Styled like ${escapeHtml(manifest.displayName)} via Open Design Library`;
  const attributionComment = isCalibre
    ? ""
    : `<!-- Styled like ${style} via Open Design Library (Apache-2.0) · upstream ${manifest.upstreamSha ?? "n/a"} -->`;

  return `<!doctype html>
<html lang="en"${themeClass ? ` class="${themeClass}"` : ""}>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<meta name="generator" content="@ohmyperf/viewer 0.0.0-pre" />
<meta name="referrer" content="no-referrer" />
<meta name="ohmyperf-style" content="${escapeHtml(style)}" />
<title>${escapeHtml(title)}</title>
<style>${paletteCss}
${STRUCTURAL_CSS}${BRAND_STRUCTURAL_OVERRIDES[style]}</style>
</head>
<body>
<div class="container">
  ${renderHero(report)}
  ${renderUnstableBanner(report)}
  ${renderCwvGrid(report)}
  ${renderAttribution(report)}
  ${renderThirdParties(report)}
  ${renderAuditsOrEmpty(report.audits)}
  ${renderResourcesOrEmpty(report)}
  ${renderFrameTree(report)}
  ${renderRunsTable(report)}
  ${renderPluginData(report.pluginData)}
  ${renderRawJson(report)}
  <p class="foot">
    Generated by <code>@ohmyperf/viewer</code>. This file is self-contained:
    no external network requests are made when you open it.${attributionSuffix}
  </p>
</div>
${attributionComment}
${embedPayload ? renderInlineReport(report) : ""}
</body>
</html>
`;
}

function renderAuditsOrEmpty(audits: ReadonlyArray<AuditResult>): string {
  if (audits.length === 0) {
    return `<h2>Audits</h2>\n${renderEmptyState("No audits configured — all plugin audits passed implicitly.", "success")}`;
  }
  return renderAudits(audits);
}

function renderResourcesOrEmpty(report: Report): string {
  const sourceRun = report.runs.find((r) => !r.cold) ?? report.runs.find((r) => r.cold) ?? report.runs[0];
  if (!sourceRun || sourceRun.resources.length === 0) {
    return `<h2>Resources</h2>\n${renderEmptyState("No resources captured in the warm run.", "info")}`;
  }
  return renderResources(report);
}

function renderHeader(report: Report): string {
  const m = report.meta;
  return `<div class="panel">
  <h1>OhMyPerf v${escapeHtml(report.schemaVersion)} report</h1>
  <dl class="meta">
    <dt>URL</dt><dd class="mono">${escapeHtml(m.url)}</dd>
    <dt>Started</dt><dd>${escapeHtml(m.startedAt)}</dd>
    <dt>Duration</dt><dd>${escapeHtml(`${String(m.durationMs)} ms`)}</dd>
    <dt>Mode</dt><dd>${escapeHtml(m.mode)} · runs=${escapeHtml(String(m.runs))} · ${escapeHtml(m.parity.mode)}</dd>
    <dt>Browser</dt><dd>${escapeHtml(`${m.browser.name} ${m.browser.version} (${m.browser.source})`)}</dd>
    <dt>Host</dt><dd>${escapeHtml(`${m.host.os} (${m.host.arch}) · Node ${m.host.nodeVersion}`)}</dd>
    <dt>Measurement ID</dt><dd class="mono">${escapeHtml(m.measurementId)}</dd>
  </dl>
</div>`;
}

function renderUnstableBanner(report: Report): string {
  const unstable = isUnstable(report);
  if (!unstable) return "";
  return `<div class="unstable-banner">
  <strong>Unstable run.</strong> At least one Core Web Vital has CoV &gt; ${escapeHtml(String(UNSTABLE_COV_THRESHOLD * 100))}% across the ${escapeHtml(String(report.runs.length))} run(s). Increase <code>--runs</code> or use <code>--mode ci-stable</code> for budget gating.
</div>`;
}

function isUnstable(report: Report): boolean {
  if (report.meta.unstable === true) return true;
  for (const name of ["lcp", "cls", "inp", "fcp", "ttfb"]) {
    const agg = report.aggregated[name];
    if (agg && Number.isFinite(agg.cov) && agg.cov > UNSTABLE_COV_THRESHOLD) return true;
  }
  return false;
}

function renderTiles(report: Report): string {
  const tiles = HEADLINE_METRICS.map(({ name, unit, digits }) => {
    const agg = report.aggregated[name];
    return renderTile(name, agg, unit, digits);
  })
    .filter((s) => s.length > 0)
    .join("\n");
  if (tiles.length === 0) return "";
  return `<h2>Aggregated metrics</h2>
<div class="tiles">
${tiles}
</div>`;
}

function renderAttribution(report: Report): string {
  const firstRun = report.runs[0];
  if (!firstRun) return "";
  const entries = Object.entries(firstRun.metrics).filter(([, m]) => m.attribution);
  if (entries.length === 0) return "";
  const blocks = entries.map(([name, metric]) => {
    const a = metric.attribution;
    if (!a) return "";
    const rows: string[] = [];
    if (a.element) rows.push(`<dt>Element</dt><dd class="mono">${escapeHtml(a.element)}</dd>`);
    if (a.url) rows.push(`<dt>Resource</dt><dd class="mono">${escapeHtml(a.url)}</dd>`);
    if (a.interactionType) rows.push(`<dt>Interaction</dt><dd>${escapeHtml(a.interactionType)}</dd>`);
    if (a.cause) rows.push(`<dt>Cause</dt><dd>${escapeHtml(a.cause)}</dd>`);
    if (a.frameId) rows.push(`<dt>Frame</dt><dd class="mono">${escapeHtml(a.frameId)}</dd>`);
    if (a.subparts) {
      const parts = Object.entries(a.subparts)
        .map(([k, v]) => `${escapeHtml(k)}=${escapeHtml(v.toFixed(0))}ms`)
        .join(" · ");
      rows.push(`<dt>Sub-parts</dt><dd>${parts}</dd>`);
    }
    if (a.longestScript) {
      const ls = a.longestScript;
      const detail = [
        ls.url ?? "(anonymous)",
        ls.invoker ?? "",
        `${ls.duration.toFixed(0)}ms`,
        `in ${ls.subpart}`,
      ]
        .filter(Boolean)
        .join(" · ");
      rows.push(`<dt>Longest script</dt><dd class="mono">${escapeHtml(detail)}</dd>`);
    }
    if (rows.length === 0) return "";
    return `<div class="panel">
    <h3>${escapeHtml(name.toUpperCase())} attribution</h3>
    <dl class="meta">${rows.join("\n      ")}</dl>
  </div>`;
  }).filter(Boolean);
  if (blocks.length === 0) return "";
  return blocks.join("\n");
}

function renderTile(
  name: string,
  agg: AggregatedMetric | undefined,
  unit: "ms" | "score",
  digits: number,
): string {
  if (!agg) return "";
  const unstable = Number.isFinite(agg.cov) && agg.cov > UNSTABLE_COV_THRESHOLD;
  const median = agg.median.toFixed(digits);
  const display = unit === "ms" ? `${median} ms` : median;
  const cov = Number.isFinite(agg.cov) ? `${(agg.cov * 100).toFixed(1)}%` : "—";
  return `  <div class="tile${unstable ? " unstable" : ""}">
    <div class="name">${escapeHtml(name.toUpperCase())}</div>
    <div class="value">${escapeHtml(display)}</div>
    <div class="sub">cov ${escapeHtml(cov)} · n=${escapeHtml(String(agg.runs))}${unstable ? " · unstable" : ""}</div>
  </div>`;
}

function renderAudits(audits: ReadonlyArray<AuditResult>): string {
  if (audits.length === 0) return "";
  const rows = audits
    .map((a) => {
      const status = a.passed ? "pass" : "fail";
      const label = a.passed ? "PASS" : "FAIL";
      return `    <tr>
      <td><span class="tag ${escapeHtml(status)}">${escapeHtml(label)}</span></td>
      <td class="mono">${escapeHtml(a.id)}</td>
      <td>${escapeHtml(a.title)}</td>
      <td>${a.score === null ? "<span class=\"muted\">—</span>" : escapeHtml(String(a.score))}</td>
    </tr>`;
    })
    .join("\n");
  return `<h2>Audits</h2>
<div class="panel" style="padding:0;overflow:hidden;">
  <table>
    <thead><tr><th>Status</th><th>ID</th><th>Title</th><th>Score</th></tr></thead>
    <tbody>
${rows}
    </tbody>
  </table>
</div>`;
}

function renderResources(report: Report): string {
  const cold = report.runs.find((r) => r.cold);
  const warm = report.runs.find((r) => !r.cold);
  const sourceRun: RunReport | undefined = warm ?? cold ?? report.runs[0];
  if (!sourceRun || sourceRun.resources.length === 0) return "";
  const resources = [...sourceRun.resources];
  resources.sort((a, b) => a.requestMs + a.responseMs - (b.requestMs + b.responseMs));

  const totalEncoded = resources.reduce((acc, r) => acc + (r.encodedSizeBytes || 0), 0);
  const totalTransfer = resources.reduce((acc, r) => acc + (r.transferSizeBytes || 0), 0);
  const renderBlocking = resources.filter((r) => r.renderBlocking).length;

  const summary = `${String(resources.length)} resources · ${formatBytes(totalEncoded)} encoded · ${formatBytes(totalTransfer)} transfer${
    renderBlocking > 0 ? ` · <span class="tag warn">${String(renderBlocking)} render-blocking</span>` : ""
  }`;

  const rows = resources
    .slice(0, 100)
    .map((r) => {
      const totalMs = (r.requestMs + r.responseMs).toFixed(1);
      const dns = r.dnsMs !== undefined ? r.dnsMs.toFixed(1) : "—";
      const tcp = r.tcpMs !== undefined ? r.tcpMs.toFixed(1) : "—";
      const tls = r.tlsMs !== undefined ? r.tlsMs.toFixed(1) : "—";
      const tags: string[] = [];
      if (r.renderBlocking) tags.push(`<span class="tag warn">render-block</span>`);
      if (r.cacheHit) tags.push(`<span class="tag pass">cache</span>`);
      return `    <tr>
      <td class="mono" style="max-width:340px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;" title="${escapeHtml(r.url)}">${escapeHtml(r.url)}</td>
      <td>${escapeHtml(r.mimeType || "—")}</td>
      <td class="mono">${escapeHtml(formatBytes(r.encodedSizeBytes))}</td>
      <td class="mono">${escapeHtml(totalMs)}</td>
      <td class="mono">${escapeHtml(dns)}/${escapeHtml(tcp)}/${escapeHtml(tls)}</td>
      <td>${tags.join(" ") || "<span class=\"muted\">—</span>"}</td>
    </tr>`;
    })
    .join("\n");

  const truncated = resources.length > 100
    ? `<p class="muted" style="margin:8px 14px 12px;">Showing first 100 of ${String(resources.length)} resources.</p>`
    : "";

  return `<h2>Resources</h2>
<div class="panel" style="padding:0;overflow:hidden;">
  <p class="muted" style="margin:12px 14px 4px;">${summary}</p>
  <table>
    <thead><tr>
      <th>URL</th><th>Type</th><th>Size</th><th>Total ms</th><th>DNS/TCP/TLS</th><th>Tags</th>
    </tr></thead>
    <tbody>
${rows}
    </tbody>
  </table>
  ${truncated}
</div>`;
}

function formatBytes(bytes: number): string {
  if (!Number.isFinite(bytes) || bytes <= 0) return "0 B";
  if (bytes < 1024) return `${String(Math.round(bytes))} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / 1024 / 1024).toFixed(2)} MB`;
}

function renderFrameTree(report: Report): string {
  const tree = report.frames;
  if (!tree.root || !tree.nodes[tree.root]) return "";
  const html = renderFrameNode(tree.nodes, tree.root);
  return `<h2>Frame tree</h2>
<div class="panel frame-tree">
${html}
</div>`;
}

function renderFrameNode(
  nodes: Readonly<Record<string, FrameNode>>,
  frameId: string,
): string {
  const node = nodes[frameId];
  if (!node) return "";
  const childrenHtml = node.children.length
    ? `<ul>${node.children.map((id) => `<li>${renderFrameNode(nodes, id)}</li>`).join("")}</ul>`
    : "";
  const tagBits: string[] = [];
  if (node.isOOPIF) tagBits.push("OOPIF");
  if (node.isCrossOrigin) tagBits.push("cross-origin");
  if (node.isSrcdoc) tagBits.push("srcdoc");
  if (node.isFenced) tagBits.push("fenced-frame");
  if (node.detachedAt !== undefined) tagBits.push("detached");
  const tags = tagBits.length
    ? ` <span class="tag warn">${escapeHtml(tagBits.join(" · "))}</span>`
    : "";
  const opaqueReason = node.inFrameMetrics?.available === false ? node.inFrameMetrics.reason : "";
  const opaque = opaqueReason
    ? ` <span class="tag warn">opaque: ${escapeHtml(opaqueReason)}</span>`
    : "";
  return `<div>
  <div><strong>${escapeHtml(node.frameId)}</strong>${tags}${opaque}</div>
  <div class="frame-url">${escapeHtml(node.url || "(empty)")}</div>
  ${childrenHtml}
</div>`;
}

function renderRunsTable(report: Report): string {
  if (report.runs.length === 0) return "";
  const metricNames = collectMetricNames(report);
  if (metricNames.length === 0) return "";
  const headerRow = `<tr><th>Run</th><th>Cold</th>${metricNames
    .map((n) => `<th class="mono">${escapeHtml(n)}</th>`)
    .join("")}</tr>`;
  const bodyRows = report.runs
    .map((r) => {
      const cells = metricNames
        .map((n) => {
          const m = r.metrics[n];
          if (!m || !Number.isFinite(m.value)) return `<td class="muted">—</td>`;
          const digits = n === "cls" ? 3 : 1;
          return `<td class="mono">${escapeHtml(m.value.toFixed(digits))}</td>`;
        })
        .join("");
      return `<tr><td>${escapeHtml(String(r.runIndex))}</td><td>${
        r.cold ? `<span class="tag warn">cold</span>` : ""
      }</td>${cells}</tr>`;
    })
    .join("\n");
  return `<h2>Per-run values</h2>
<div class="panel" style="padding:0;overflow:hidden;">
  <table>
    <thead>${headerRow}</thead>
    <tbody>${bodyRows}</tbody>
  </table>
</div>`;
}

function collectMetricNames(report: Report): string[] {
  const seen = new Set<string>();
  for (const r of report.runs) {
    for (const k of Object.keys(r.metrics)) seen.add(k);
  }
  return [...seen].sort();
}

function renderPluginData(pluginData: Readonly<Record<string, unknown>>): string {
  const keys = Object.keys(pluginData);
  if (keys.length === 0) return "";
  const blocks = keys
    .map((k) => {
      const json = JSON.stringify(pluginData[k], null, 2);
      return `<details>
  <summary>${escapeHtml(k)}</summary>
  <pre class="code">${escapeHtml(json)}</pre>
</details>`;
    })
    .join("\n");
  return `<h2>Plugin data</h2>
<div class="panel">
${blocks}
</div>`;
}

function renderRawJson(report: Report): string {
  const json = JSON.stringify(report, null, 2);
  return `<h2>Raw report</h2>
<details>
  <summary>Show raw JSON</summary>
  <pre class="code">${escapeHtml(json)}</pre>
</details>`;
}

function renderInlineReport(report: Report): string {
  return `<script type="application/json" id="ohmyperf-report-payload">${escapeJsonForHtml(report)}</script>
<script>
  (function () {
    try {
      var el = document.getElementById("ohmyperf-report-payload");
      if (el && el.textContent) {
        window.__OHMYPERF_REPORT__ = JSON.parse(el.textContent);
      }
    } catch (e) {
      console.warn("ohmyperf: could not parse embedded report payload", e);
    }
  })();
</script>`;
}

function shortenUrl(url: string): string {
  try {
    const u = new URL(url);
    return `${u.host}${u.pathname === "/" ? "" : u.pathname}`;
  } catch {
    return url;
  }
}
