export default {};
export const randomUUID = () => Math.random().toString(36).slice(2) + Date.now().toString(36);
export const arch = () => 'browser';
export const platform = () => 'browser';
export const release = () => '';
export const homedir = () => '';
export const hostname = () => 'extension';
export const totalmem = () => 0;
export const createHash = () => ({ update() { return this; }, digest() { return ''; } });
export const readFile = async () => { throw new Error('node:fs/promises not available in browser bundle'); };
export const writeFile = async () => undefined;
export const mkdir = async () => undefined;
export const unlink = async () => undefined;
export const existsSync = () => false;
export const join = (...p) => p.join('/');
export const dirname = (p) => p.split('/').slice(0, -1).join('/');
export const resolve = (...p) => p.join('/');
