import type { AggregatedMetric, Metric, Report, RunReport } from "@ohmyperf/core";

export const REPORTER_ID = "markdown" as const;

export interface MarkdownReporterOptions {
  readonly fileName?: string;
  readonly title?: string;
  readonly includePluginData?: boolean;
}

export interface MarkdownReporterResult {
  readonly path: string;
  readonly bytes: number;
}

const HEADLINE_METRICS = ["lcp", "fcp", "ttfb", "inp", "cls", "tbt"] as const;
const UNSTABLE_COV_THRESHOLD = 0.2;

export function renderMarkdown(report: Report, opts: MarkdownReporterOptions = {}): string {
  const title = opts.title ?? "OhMyPerf report";
  const lines: string[] = [];
  lines.push(`## ${title}`);
  lines.push("");
  lines.push(`- **URL**: \`${report.meta.url}\``);
  lines.push(
    `- **Mode**: \`${report.meta.mode}\` · **Runs**: ${String(report.meta.runs)} · **Headless**: \`${report.meta.parity.mode}\``,
  );
  lines.push(
    `- **Browser**: \`${report.meta.browser.name} ${report.meta.browser.version}\` (${report.meta.browser.source})`,
  );
  if (report.meta.calibration) {
    lines.push(
      `- **Calibration**: throttle ${report.meta.calibration.throttleRate}× · ${report.meta.calibration.networkProfile}` +
        (report.meta.calibration.cacheHit ? " · cached" : ""),
    );
  }
  if (report.meta.unstable) {
    lines.push(`- ⚠️ **Unstable run** — at least one CWV has CoV > 20%.`);
  }
  lines.push("");

  lines.push("### Core Web Vitals");
  lines.push("");
  lines.push("| Metric | Median | p75 | p95 | CoV | n |");
  lines.push("|--------|-------:|----:|----:|----:|---:|");
  for (const name of HEADLINE_METRICS) {
    const agg = report.aggregated[name];
    if (!agg) continue;
    lines.push(formatAggregatedRow(name, agg));
  }
  lines.push("");

  if (report.audits.length > 0) {
    lines.push("### Audits");
    lines.push("");
    lines.push("| Status | ID | Title |");
    lines.push("|--------|----|-------|");
    for (const a of report.audits) {
      const status = a.passed ? "✅ PASS" : "❌ FAIL";
      lines.push(
        `| ${status} | \`${escapeMd(a.id)}\` | ${escapeMd(a.title)} |`,
      );
    }
    lines.push("");
  }

  const sourceRun = report.runs.find((r) => !r.cold) ?? report.runs[0];

  renderInsightsSection(lines, report, sourceRun);

  if (sourceRun && sourceRun.resources.length > 0) {
    const totalBytes = sourceRun.resources.reduce((acc, r) => acc + (r.encodedSizeBytes || 0), 0);
    const renderBlocking = sourceRun.resources.filter((r) => r.renderBlocking).length;
    lines.push("### Resources");
    lines.push("");
    lines.push(
      `- ${String(sourceRun.resources.length)} resources · ${formatBytes(totalBytes)} total${
        renderBlocking > 0 ? ` · ${String(renderBlocking)} render-blocking` : ""
      }`,
    );
    lines.push("");
  }

  if (opts.includePluginData) {
    const keys = Object.keys(report.pluginData);
    if (keys.length > 0) {
      lines.push("### Plugin data");
      lines.push("");
      lines.push("<details>");
      lines.push("<summary>Show JSON</summary>");
      lines.push("");
      lines.push("```json");
      lines.push(JSON.stringify(report.pluginData, null, 2));
      lines.push("```");
      lines.push("");
      lines.push("</details>");
      lines.push("");
    }
  }

  lines.push(`<sub>Generated by OhMyPerf v${report.schemaVersion} · ${report.meta.measurementId}</sub>`);
  lines.push("");
  return lines.join("\n");
}

function formatAggregatedRow(name: string, agg: AggregatedMetric): string {
  const digits = name === "cls" ? 3 : 1;
  const median = formatValue(agg.median, name, digits);
  const p75 = formatValue(agg.p75, name, digits);
  const p95 = formatValue(agg.p95, name, digits);
  const covPct = (agg.cov * 100).toFixed(1) + "%";
  const unstableMark = agg.cov > UNSTABLE_COV_THRESHOLD ? " ⚠️" : "";
  return `| **${name.toUpperCase()}** | ${median} | ${p75} | ${p95} | ${covPct}${unstableMark} | ${String(agg.runs)} |`;
}

function formatValue(value: number, name: string, digits: number): string {
  if (!Number.isFinite(value)) return "—";
  if (name === "cls") return value.toFixed(digits);
  return `${value.toFixed(digits)} ms`;
}

function formatBytes(bytes: number): string {
  if (!Number.isFinite(bytes) || bytes <= 0) return "0 B";
  if (bytes < 1024) return `${String(Math.round(bytes))} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / 1024 / 1024).toFixed(2)} MB`;
}

function escapeMd(s: string): string {
  return s.replace(/[|\\`]/g, (ch) => `\\${ch}`);
}

function renderInsightsSection(
  lines: string[],
  report: Report,
  sourceRun: RunReport | undefined,
): void {
  if (!sourceRun) return;
  const lcp = sourceRun.metrics["lcp"];
  const inp = sourceRun.metrics["inp"];
  const renderBlocking = (sourceRun.opportunities ?? []).find(
    (o) => o.id === "render-blocking-resources",
  );
  const longTasks = sourceRun.longTasks;
  const thirdParty = report.audits.find((a) => a.id === "third-parties");

  const hasInsight = !!(
    lcp?.attribution?.subparts ||
    inp?.attribution?.subparts ||
    renderBlocking ||
    longTasks.length > 0 ||
    thirdParty
  );
  if (!hasInsight) return;

  lines.push("## Insights");
  lines.push("");

  if (lcp?.attribution) {
    lines.push(formatLcpInsight(lcp));
    lines.push("");
  }
  if (inp?.attribution) {
    lines.push(formatInpInsight(inp));
    lines.push("");
  }
  if (renderBlocking) {
    lines.push(`**Render-blocking resources** — ${(renderBlocking.wastedMs ?? 0).toFixed(0)}ms wasted on FCP`);
    lines.push("");
    if (renderBlocking.items.length > 0) {
      lines.push("| Resource | Wasted (ms) | Size (KB) |");
      lines.push("|---|---:|---:|");
      for (const it of renderBlocking.items.slice(0, 5)) {
        const ms = it.wastedMs !== undefined ? it.wastedMs.toFixed(0) : "—";
        const kb = it.wastedBytes !== undefined ? (it.wastedBytes / 1024).toFixed(1) : "—";
        lines.push(`| \`${escapeMd(truncate(it.url, 80))}\` | ${ms} | ${kb} |`);
      }
      lines.push("");
    }
  }
  if (longTasks.length > 0) {
    const top = [...longTasks].sort((a, b) => b.duration - a.duration).slice(0, 5);
    lines.push(`**Top long tasks** (${String(longTasks.length)} total)`);
    lines.push("");
    lines.push("| URL | Start (ms) | Duration (ms) |");
    lines.push("|---|---:|---:|");
    for (const t of top) {
      const url = t.attributionRich?.url ?? "(anonymous)";
      lines.push(`| \`${escapeMd(truncate(url, 80))}\` | ${t.startTime.toFixed(0)} | ${t.duration.toFixed(0)} |`);
    }
    lines.push("");
  }
  if (thirdParty?.details) {
    const details = thirdParty.details as { items?: Array<{ entity: string; category: string; transferSize: number; mainThreadTime: number }> };
    const items = (details.items ?? []).slice(0, 5);
    if (items.length > 0) {
      lines.push(`**Third parties**`);
      lines.push("");
      lines.push("| Entity | Category | Transfer (KB) | Main thread (ms) |");
      lines.push("|---|---|---:|---:|");
      for (const it of items) {
        lines.push(
          `| ${escapeMd(it.entity)} | \`${escapeMd(it.category)}\` | ${(it.transferSize / 1024).toFixed(1)} | ${it.mainThreadTime.toFixed(0)} |`,
        );
      }
      lines.push("");
    }
  }
}

function formatLcpInsight(metric: Metric): string {
  const a = metric.attribution;
  if (!a) return "";
  const parts: string[] = [`**LCP** — ${metric.value.toFixed(0)}ms`];
  if (a.element) parts.push(`element \`${escapeMd(a.element)}\``);
  if (a.url) parts.push(`resource \`${escapeMd(truncate(a.url, 60))}\``);
  if (a.subparts) {
    const sp = Object.entries(a.subparts)
      .map(([k, v]) => `${k}=${v.toFixed(0)}ms`)
      .join(" · ");
    parts.push(`sub-parts: ${sp}`);
  }
  return `- ${parts.join(" · ")}`;
}

function formatInpInsight(metric: Metric): string {
  const a = metric.attribution;
  if (!a) return "";
  const parts: string[] = [`**INP** — ${metric.value.toFixed(0)}ms`];
  if (a.element) parts.push(`target \`${escapeMd(a.element)}\``);
  if (a.interactionType) parts.push(`${a.interactionType}`);
  if (a.subparts) {
    const sp = Object.entries(a.subparts)
      .map(([k, v]) => `${k}=${v.toFixed(0)}ms`)
      .join(" · ");
    parts.push(`sub-parts: ${sp}`);
  }
  if (a.longestScript) {
    parts.push(
      `longest script: \`${escapeMd(truncate(a.longestScript.url ?? "(anonymous)", 60))}\` (${a.longestScript.duration.toFixed(0)}ms)`,
    );
  }
  return `- ${parts.join(" · ")}`;
}

function truncate(s: string, n: number): string {
  return s.length > n ? s.slice(0, n - 1) + "…" : s;
}
